let cards = [
  { name: '2C', value: 2, suit: 'C', image: 'images/2C.png' },
  { name: '2D', value: 2, suit: 'D', image: 'images/2D.png' },
  { name: '2H', value: 2, suit: 'H', image: 'images/2H.png' },
  { name: '2S', value: 2, suit: 'S', image: 'images/2S.png' },
  { name: '3C', value: 3, suit: 'C', image: 'images/3C.png' },
  { name: '3D', value: 3, suit: 'D', image: 'images/3D.png' },
  { name: '3H', value: 3, suit: 'H', image: 'images/3H.png' },
  { name: '3S', value: 3, suit: 'S', image: 'images/3S.png' },
  { name: '4C', value: 4, suit: 'C', image: 'images/4C.png' },
  { name: '4D', value: 4, suit: 'D', image: 'images/4D.png' },
  { name: '4H', value: 4, suit: 'H', image: 'images/4H.png' },
  { name: '4S', value: 4, suit: 'S', image: 'images/4S.png' },
  { name: '5C', value: 5, suit: 'C', image: 'images/5C.png' },
  { name: '5D', value: 5, suit: 'D', image: 'images/5D.png' },
  { name: '5H', value: 5, suit: 'H', image: 'images/5H.png' },
  { name: '5S', value: 5, suit: 'S', image: 'images/5S.png' },
  { name: '6C', value: 6, suit: 'C', image: 'images/6C.png' },
  { name: '6D', value: 6, suit: 'D', image: 'images/6D.png' },
  { name: '6H', value: 6, suit: 'H', image: 'images/6H.png' },
  { name: '6S', value: 6, suit: 'S', image: 'images/6S.png' },
  { name: '7C', value: 7, suit: 'C', image: 'images/7C.png' },
  { name: '7D', value: 7, suit: 'D', image: 'images/7D.png' },
  { name: '7H', value: 7, suit: 'H', image: 'images/7H.png' },
  { name: '7S', value: 7, suit: 'S', image: 'images/7S.png' },
  { name: '8C', value: 8, suit: 'C', image: 'images/8C.png' },
  { name: '8D', value: 8, suit: 'D', image: 'images/8D.png' },
  { name: '8H', value: 8, suit: 'H', image: 'images/8H.png' },
  { name: '8S', value: 8, suit: 'S', image: 'images/8S.png' },
  { name: '9C', value: 9, suit: 'C', image: 'images/9C.png' },
  { name: '9D', value: 9, suit: 'D', image: 'images/9D.png' },
  { name: '9H', value: 9, suit: 'H', image: 'images/9H.png' },
  { name: '9S', value: 9, suit: 'S', image: 'images/9S.png' },
  { name: '10C', value: 10, suit: 'C', image: 'images/10C.png' },
  { name: '10D', value: 10, suit: 'D', image: 'images/10D.png' },
  { name: '10H', value: 10, suit: 'H', image: 'images/10H.png' },
  { name: '10S', value: 10, suit: 'S', image: 'images/10S.png' },
  { name: 'JC', value: 10, suit: 'C', image: 'images/JC.png' },
  { name: 'JD', value: 10, suit: 'D', image: 'images/JD.png' },
  { name: 'JH', value: 10, suit: 'H', image: 'images/JH.png' },
  { name: 'JS', value: 10, suit: 'S', image: 'images/JS.png' },
  { name: 'QC', value: 10, suit: 'C', image: 'images/QC.png' },
  { name: 'QD', value: 10, suit: 'D', image: 'images/QD.png' },
  { name: 'QH', value: 10, suit: 'H', image: 'images/QH.png' },
  { name: 'QS', value: 10, suit: 'S', image: 'images/QS.png' },
  { name: 'KC', value: 10, suit: 'C', image: 'images/KC.png' },
  { name: 'KD', value: 10, suit: 'D', image: 'images/KD.png' },
  { name: 'KH', value: 10, suit: 'H', image: 'images/KH.png' },
  { name: 'KS', value: 10, suit: 'S', image: 'images/KS.png' },
  { name: 'AC', value: [1, 11], suit: 'C', image: 'images/AC.png' },
  { name: 'AD', value: [1, 11], suit: 'D', image: 'images/AD.png' },
  { name: 'AH', value: [1, 11], suit: 'H', image: 'images/AH.png' },
  { name: 'AS', value: [1, 11], suit: 'S', image: 'images/AS.png' },
]
